== Conclusiones <conclusiones>

La evidencia presentada a través de fuentes oficiales y el pronunciamiento de autoridades especializadas en derechos humanos confirma inequívocamente que la crisis de violencia sexual en el sistema educativo peruano constituye una violación sistemática y masiva de los derechos fundamentales de los menores. Las cifras del Ministerio de Educación, que documentan más de 15,000 casos en la última década, junto con la impunidad absoluta evidenciada en las comunidades indígenas amazónicas, revelan fallas estructurales profundas que trascienden la responsabilidad individual de los agresores.

Los pronunciamientos de Human Rights Watch y del Comité de los Derechos del Niño de las Naciones Unidas sitúan esta crisis en el contexto de las obligaciones internacionales del Estado peruano y evidencian el incumplimiento sistemático de estándares mínimos de protección infantil. La autoridad moral y jurídica de estas instituciones, respaldada por décadas de experiencia en la defensa de derechos humanos, otorga particular gravedad a sus hallazgos y recomendaciones.

La persistencia de esta problemática, documentada tanto por fuentes oficiales nacionales como por organismos internacionales, demuestra que las medidas adoptadas hasta la fecha han sido claramente insuficientes. La impunidad sistemática, la falta de mecanismos efectivos de prevención y la ausencia de programas integrales de educación sexual constituyen factores que perpetúan un ciclo de violencia que vulnera el derecho constitucional de los menores a una educación segura.

La tesis planteada se confirma plenamente: la crisis de violencia sexual en el sistema educativo peruano requiere una respuesta integral y urgente del Estado que incluya reformas estructurales profundas. Solo a través de un compromiso institucional genuino con la erradicación de la impunidad, el fortalecimiento de mecanismos de prevención y detección, y la implementación de programas de educación sexual integral, será posible garantizar que las escuelas cumplan su función fundamental de espacios seguros para el desarrollo integral de los menores.

El costo de la inacción es inconmensurable: cada día que transcurre sin medidas efectivas representa no solo la perpetuación del sufrimiento de miles de menores, sino también la reproducción de patrones de violencia que marcarán a generaciones futuras. La protección de la infancia no es solo un imperativo legal y moral, sino una inversión fundamental en el futuro de la sociedad peruana.
